import {and,eq,isNull,sql} from 'drizzle-orm';
import {randomUUID} from 'node:crypto';
import {getDb} from '../db';
import {artists,studios,tenantMaterials,studioMaterialArtists,appointments,whatsappIntegrations,suppliers} from '../../drizzle/schema';
import {artistCards,procurementAlerts,procurementQuotes,procurementContacts} from '../../drizzle/studioRelationsSchema';
import {getProviderForIntegration,getAffectedRows} from './service';
import {normalizeBrazilianPhone} from './phone';
export async function artistCardLink(studioId:number,appointmentId:number){const d=await getDb();if(!d)return '';const a=(await d.select().from(appointments).where(and(eq(appointments.id,appointmentId),eq(appointments.studioId,studioId))).limit(1))[0];if(!a?.artistId)return '';const row=(await d.select({token:artistCards.token}).from(artistCards).innerJoin(artists,and(eq(artists.id,artistCards.artistId),eq(artists.studioId,studioId),eq(artists.active,1))).where(and(eq(artistCards.artistId,a.artistId),eq(artistCards.studioId,studioId),eq(artistCards.published,1))).limit(1))[0];const origin=process.env.PUBLIC_URL||process.env.APP_BASE_URL||(process.env.RAILWAY_PUBLIC_DOMAIN?`https://${process.env.RAILWAY_PUBLIC_DOMAIN}`:'');return row&&origin?`${origin.replace(/\/$/,'')}/artista/${row.token}`:'';}
const stamp=()=>new Date().toISOString().slice(0,19).replace('T',' ');
async function connection(studioId:number,phone:string){const d=await getDb();if(!d)throw new Error('Banco indisponível.');const i=(await d.select().from(whatsappIntegrations).where(and(eq(whatsappIntegrations.studioId,studioId),eq(whatsappIntegrations.status,'ativo'),eq(whatsappIntegrations.isEnabled,1))).limit(1))[0];if(!i)throw new Error('Configure e teste uma conexão WhatsApp ativa.');if(i.sandboxMode&&normalizeBrazilianPhone(phone)!==normalizeBrazilianPhone(i.sandboxTestPhone||''))throw new Error('O destinatário não é o telefone autorizado para teste.');return getProviderForIntegration(i);}
export async function runProcurementCycle(){const d=await getDb();if(!d)return;
 const materials=await d.select().from(tenantMaterials).where(and(isNull(tenantMaterials.ownerArtistId),eq(tenantMaterials.isActive,1)));
 for(const m of materials){let alert=(await d.select().from(procurementAlerts).where(and(eq(procurementAlerts.studioId,m.studioId),eq(procurementAlerts.materialId,m.id))).limit(1))[0];const low=Number(m.minimumQuantity)>0&&Number(m.currentQuantity)<=Number(m.minimumQuantity);
 if(!low){if(alert?.status==='open')await d.update(procurementAlerts).set({status:'resolved'}).where(eq(procurementAlerts.id,alert.id));continue;}
 if(!alert){await d.insert(procurementAlerts).values({studioId:m.studioId,materialId:m.id,episode:randomUUID()}).onDuplicateKeyUpdate({set:{materialId:m.id}});continue;}
 if(alert.status==='resolved'){await d.update(procurementAlerts).set({status:'open',episode:randomUUID(),notifiedAt:null,lastError:null}).where(eq(procurementAlerts.id,alert.id));continue;}
 if(!alert.notifyEnabled||alert.notifiedAt||alert.status!=='open')continue;
 try {let phone='';let name='equipe';if(alert.recipientArtistId){const link=(await d.select().from(studioMaterialArtists).where(and(eq(studioMaterialArtists.studioId,m.studioId),eq(studioMaterialArtists.tenantMaterialId,m.id),eq(studioMaterialArtists.artistId,alert.recipientArtistId))).limit(1))[0];if(!link)throw new Error('Este material deixou de ser disponibilizado ao artista.');const a=(await d.select().from(artists).where(and(eq(artists.studioId,m.studioId),eq(artists.id,alert.recipientArtistId),eq(artists.active,1))).limit(1))[0];phone=a?.phone||'';name=a?.name?.split(' ')[0]||'artista';}else{const studio=(await d.select().from(studios).where(eq(studios.id,m.studioId)).limit(1))[0];phone=studio?.phone||'';}
 phone=normalizeBrazilianPhone(phone)||'';if(!phone)throw new Error('Preencha o telefone do destinatário no cadastro.');const provider=await connection(m.studioId,phone);
 // Reserve before the external call. An uncertain result needs review, never an automatic duplicate.
 const claimed=await d.update(procurementAlerts).set({notifiedAt:stamp(),lastError:'Envio iniciado; verifique o provedor se não houver confirmação.'}).where(and(eq(procurementAlerts.id,alert.id),isNull(procurementAlerts.notifiedAt)));if(!getAffectedRows(claimed))continue;
 const origin=process.env.PUBLIC_URL||process.env.APP_BASE_URL||(process.env.RAILWAY_PUBLIC_DOMAIN?`https://${process.env.RAILWAY_PUBLIC_DOMAIN}`:'');
 const result=await provider.sendMessage(phone,`Olá, ${name}! O material ${m.name}, fornecido pelo estúdio, precisa de reposição: restam ${m.currentQuantity} ${m.unit} (mínimo ${m.minimumQuantity}). Podemos solicitar um orçamento aos fornecedores? Peça ao responsável para revisar e aprovar em Estoque → Reposição e orçamentos.${origin?' '+origin+'/stock':''}`);
 await d.update(procurementAlerts).set({lastError:result.success?null:result.error||'Envio não confirmado; revise antes de reenviar.'}).where(eq(procurementAlerts.id,alert.id));
 }catch(e){await d.update(procurementAlerts).set({lastError:e instanceof Error?e.message:'Aviso não confirmado.'}).where(eq(procurementAlerts.id,alert.id));}
 }
 const quotes=await d.select().from(procurementQuotes).where(eq(procurementQuotes.status,'approved')).limit(10);
 for(const q of quotes){let claimed=false;try{const contact=(await d.select().from(procurementContacts).innerJoin(suppliers,eq(suppliers.id,procurementContacts.supplierId)).where(and(eq(procurementContacts.studioId,q.studioId),eq(procurementContacts.supplierId,q.supplierId),eq(suppliers.isActive,1))).limit(1))[0];if(!contact)throw new Error('Fornecedor não está mais autorizado.');const phone=normalizeBrazilianPhone(contact.suppliers.whatsapp||contact.suppliers.phone||'');if(phone!==q.recipientPhone)throw new Error('Telefone do fornecedor mudou. Prepare um novo rascunho.');if(!q.approvedBy||!q.approvedAt)throw new Error('Aprovação ausente.');const provider=await connection(q.studioId,q.recipientPhone);const reserved=await d.update(procurementQuotes).set({status:'processing'}).where(and(eq(procurementQuotes.id,q.id),eq(procurementQuotes.status,'approved')));if(!getAffectedRows(reserved))continue;claimed=true;const result=await provider.sendMessage(q.recipientPhone,q.message);await d.update(procurementQuotes).set(result.success?{status:'sent',sentAt:stamp(),providerMessageId:result.messageId,lastError:null}:{status:'review',lastError:result.error||'Envio não confirmado; confira o provedor.'}).where(eq(procurementQuotes.id,q.id));}catch(e){await d.update(procurementQuotes).set({status:claimed?'review':'blocked',lastError:e instanceof Error?e.message:'Envio não confirmado.'}).where(and(eq(procurementQuotes.id,q.id),eq(procurementQuotes.status,claimed?'processing':'approved')));}}
}
