import {materialDescription} from "../../shared/materialDescription";
import {z} from 'zod';
import {TRPCError} from '@trpc/server';
import {and,eq,isNull,lte,gt,desc} from 'drizzle-orm';
import {randomBytes,randomUUID} from 'node:crypto';
import {router,tenantProcedure,publicProcedure} from '../_core/trpc';
import {getDb} from '../db';
import {artists,studios,suppliers,tenantMaterials,studioMaterialArtists,whatsappIntegrations} from '../../drizzle/schema';
import {artistCards,procurementContacts,procurementTemplates,procurementQuotes,procurementAlerts} from '../../drizzle/studioRelationsSchema';
import {avatarSchema,decodeAvatar} from '../artistAvatar';
import {storagePut} from '../storage';
import {QUOTE_MODELS,renderQuote,safePublicUrl,QUOTE_VARIABLES,normalizeCardLinks} from '../../shared/studioRelations';
import {parsePresentation,toPublicPresentation,artistCardPresentationPatchSchema} from '../../shared/artistCardPresentation';
import {normalizeBrazilianPhone} from '../messaging/phone';
const database=async()=>{const d=await getDb();if(!d)throw new TRPCError({code:'INTERNAL_SERVER_ERROR'});return d;};
const manager=(ctx:any)=>{if(!['admin','superadmin'].includes(ctx.user.role))throw new TRPCError({code:'FORBIDDEN'});};
const stamp=()=>new Date().toISOString().slice(0,19).replace('T',' ');
async function artistAccess(ctx:any,id:number){const d=await database();const artist=(await d.select().from(artists).where(and(eq(artists.id,id),eq(artists.studioId,ctx.studioId))).limit(1))[0];if(!artist||(ctx.user.role==='collaborator'&&ctx.artistId!==id))throw new TRPCError({code:'FORBIDDEN'});return artist;}
const linkSchema=z.object({label:z.string().trim().max(40),url:z.string().max(500)});
export const studioRelationsRouter=router({
 card:tenantProcedure.input(z.object({artistId:z.number()})).query(async({ctx,input})=>{await artistAccess(ctx,input.artistId);const d=await database();const row=(await d.select().from(artistCards).where(and(eq(artistCards.studioId,ctx.studioId),eq(artistCards.artistId,input.artistId))).limit(1))[0];if(!row)return null;const artist=(await d.select({name:artists.name,photoUrl:artists.photoUrl}).from(artists).where(eq(artists.id,input.artistId)).limit(1))[0];return{...row,links:JSON.parse(row.links) as {label:string,url:string}[],images:JSON.parse(row.images) as {key:string,url:string,caption:string}[],presentation:parsePresentation(row.presentation),artistName:artist?.name,artistPhoto:artist?.photoUrl};}),
 saveCard:tenantProcedure.input(z.object({artistId:z.number(),headline:z.string().max(160),description:z.string().max(3000),links:z.array(linkSchema).max(8),published:z.boolean(),presentation:artistCardPresentationPatchSchema.optional()})).mutation(async({ctx,input})=>{await artistAccess(ctx,input.artistId);const d=await database();let links;try{links=normalizeCardLinks(input.links);}catch(e){throw new TRPCError({code:'BAD_REQUEST',message:(e as Error).message});}const data:any={headline:input.headline,description:input.description,links:JSON.stringify(links),published:input.published?1:0};if(input.presentation){const row=(await d.select().from(artistCards).where(and(eq(artistCards.studioId,ctx.studioId),eq(artistCards.artistId,input.artistId))).limit(1))[0];const existing=row?parsePresentation(row.presentation):null;const merged={version:1 as const,quote:input.presentation.quote??existing?.quote,tagline:input.presentation.tagline??existing?.tagline,specialties:input.presentation.specialties??existing?.specialties,techniques:input.presentation.techniques??existing?.techniques,education:input.presentation.education??existing?.education,experience:input.presentation.experience??existing?.experience,location:input.presentation.location??existing?.location,cover:existing?.cover,about:existing?.about,process:existing?.process};data.presentation=JSON.stringify(merged);}await d.insert(artistCards).values({...data,studioId:ctx.studioId,artistId:input.artistId,token:randomBytes(24).toString('hex'),images:'[]'}).onDuplicateKeyUpdate({set:data});return{ok:true};}),
 uploadWork:tenantProcedure.input(avatarSchema.extend({artistId:z.number(),caption:z.string().max(160)})).mutation(async({ctx,input})=>{await artistAccess(ctx,input.artistId);const buffer=decodeAvatar(input);const d=await database();await d.insert(artistCards).values({studioId:ctx.studioId,artistId:input.artistId,token:randomBytes(24).toString('hex'),published:0,headline:'',description:'',links:'[]',images:'[]'}).onDuplicateKeyUpdate({set:{artistId:input.artistId}});const row=(await d.select().from(artistCards).where(and(eq(artistCards.studioId,ctx.studioId),eq(artistCards.artistId,input.artistId))).limit(1))[0];if(!row)throw new TRPCError({code:'BAD_REQUEST',message:'Salve o cartão antes de adicionar trabalhos.'});const key=`artists/${ctx.studioId}/${input.artistId}/portfolio/${randomUUID()}.${input.mimeType==='image/jpeg'?'jpg':input.mimeType.split('/')[1]}`;const uploaded=await storagePut(key,buffer,input.mimeType);await d.transaction(async tx=>{const current=(await tx.select().from(artistCards).where(eq(artistCards.id,row.id)).for('update'))[0];const images=JSON.parse(current.images);if(images.length>=12)throw new TRPCError({code:'BAD_REQUEST',message:'Limite de 12 trabalhos por cartão.'});images.push({key,url:uploaded.url,caption:input.caption});await tx.update(artistCards).set({images:JSON.stringify(images)}).where(eq(artistCards.id,row.id));});return{ok:true};}),
 removeWork:tenantProcedure.input(z.object({artistId:z.number(),key:z.string()})).mutation(async({ctx,input})=>{await artistAccess(ctx,input.artistId);const d=await database();await d.transaction(async tx=>{const row=(await tx.select().from(artistCards).where(and(eq(artistCards.studioId,ctx.studioId),eq(artistCards.artistId,input.artistId))).for('update'))[0];if(!row)throw new TRPCError({code:'NOT_FOUND'});await tx.update(artistCards).set({images:JSON.stringify(JSON.parse(row.images).filter((x:any)=>x.key!==input.key))}).where(eq(artistCards.id,row.id));});return{ok:true};}),
 uploadPresentationMedia:tenantProcedure.input(avatarSchema.extend({artistId:z.number(),slot:z.enum(['cover','about','process']),alt:z.string().max(200),x:z.number().min(0).max(100),y:z.number().min(0).max(100)})).mutation(async({ctx,input})=>{await artistAccess(ctx,input.artistId);const buffer=decodeAvatar(input);const d=await database();await d.insert(artistCards).values({studioId:ctx.studioId,artistId:input.artistId,token:randomBytes(24).toString('hex'),published:0,headline:'',description:'',links:'[]',images:'[]'}).onDuplicateKeyUpdate({set:{artistId:input.artistId}});const row=(await d.select().from(artistCards).where(and(eq(artistCards.studioId,ctx.studioId),eq(artistCards.artistId,input.artistId))).limit(1))[0];if(!row)throw new TRPCError({code:'BAD_REQUEST',message:'Salve o cartão antes de adicionar mídia.'});const key=`artists/${ctx.studioId}/${input.artistId}/card/${input.slot}/${randomUUID()}.${input.mimeType==='image/jpeg'?'jpg':input.mimeType.split('/')[1]}`;const uploaded=await storagePut(key,buffer,input.mimeType);await d.transaction(async tx=>{const current=(await tx.select().from(artistCards).where(eq(artistCards.id,row.id)).for('update'))[0];const presentation=parsePresentation(current.presentation)||{version:1 as const};presentation[input.slot as 'cover'|'about'|'process']={key,url:uploaded.url,alt:input.alt,x:input.x,y:input.y};await tx.update(artistCards).set({presentation:JSON.stringify(presentation)}).where(eq(artistCards.id,row.id));});return{ok:true};}),
 updateMediaFocal:tenantProcedure.input(z.object({artistId:z.number(),slot:z.enum(['cover','about','process']),expectedKey:z.string(),alt:z.string().max(200),x:z.number().min(0).max(100),y:z.number().min(0).max(100)})).mutation(async({ctx,input})=>{await artistAccess(ctx,input.artistId);const d=await database();await d.transaction(async tx=>{const row=(await tx.select().from(artistCards).where(and(eq(artistCards.studioId,ctx.studioId),eq(artistCards.artistId,input.artistId))).for('update'))[0];if(!row)throw new TRPCError({code:'NOT_FOUND'});const presentation=parsePresentation(row.presentation);const current=presentation?.[input.slot as 'cover'|'about'|'process'];if(!current||current.key!==input.expectedKey)throw new TRPCError({code:'CONFLICT',message:'Mídia foi alterada. Recarregue e tente novamente.'});current.alt=input.alt;current.x=input.x;current.y=input.y;await tx.update(artistCards).set({presentation:JSON.stringify(presentation)}).where(eq(artistCards.id,row.id));});return{ok:true};}),
 removePresentationMedia:tenantProcedure.input(z.object({artistId:z.number(),slot:z.enum(['cover','about','process'])})).mutation(async({ctx,input})=>{await artistAccess(ctx,input.artistId);const d=await database();await d.transaction(async tx=>{const row=(await tx.select().from(artistCards).where(and(eq(artistCards.studioId,ctx.studioId),eq(artistCards.artistId,input.artistId))).for('update'))[0];if(!row)throw new TRPCError({code:'NOT_FOUND'});const presentation=parsePresentation(row.presentation)||{version:1 as const};presentation[input.slot as 'cover'|'about'|'process']=null;await tx.update(artistCards).set({presentation:JSON.stringify(presentation)}).where(eq(artistCards.id,row.id));});return{ok:true};}),
 publicCard:publicProcedure.input(z.object({token:z.string().regex(/^[a-f0-9]{48}$/)})).query(async({input})=>{const d=await database();const row=(await d.select({name:artists.name,photo:artists.photoUrl,headline:artistCards.headline,description:artistCards.description,links:artistCards.links,images:artistCards.images,presentationJson:artistCards.presentation}).from(artistCards).innerJoin(artists,and(eq(artists.id,artistCards.artistId),eq(artists.studioId,artistCards.studioId),eq(artists.active,1))).where(and(eq(artistCards.token,input.token),eq(artistCards.published,1))).limit(1))[0];if(!row)throw new TRPCError({code:'NOT_FOUND',message:'Cartão não publicado.'});return{...row,links:JSON.parse(row.links) as {label:string,url:string}[],images:JSON.parse(row.images) as {url:string,caption:string}[],presentationJson:row.presentationJson};}),
 procurement:tenantProcedure.query(async({ctx})=>{manager(ctx);const d=await database();return{materials:await d.select().from(tenantMaterials).where(and(eq(tenantMaterials.studioId,ctx.studioId),isNull(tenantMaterials.ownerArtistId),eq(tenantMaterials.isActive,1))),contacts:await d.select({id:suppliers.id,name:suppliers.name}).from(procurementContacts).innerJoin(suppliers,eq(suppliers.id,procurementContacts.supplierId)).where(and(eq(procurementContacts.studioId,ctx.studioId),eq(suppliers.studioId,ctx.studioId),eq(suppliers.isActive,1))),templates:await d.select().from(procurementTemplates).where(eq(procurementTemplates.studioId,ctx.studioId)),alerts:await d.select().from(procurementAlerts).where(eq(procurementAlerts.studioId,ctx.studioId)),quotes:await d.select().from(procurementQuotes).where(eq(procurementQuotes.studioId,ctx.studioId)).orderBy(desc(procurementQuotes.id)).limit(100),};}),
 authorizeSupplier:tenantProcedure.input(z.object({supplierId:z.number(),confirmed:z.literal(true)})).mutation(async({ctx,input})=>{manager(ctx);const d=await database();const supplier=(await d.select().from(suppliers).where(and(eq(suppliers.id,input.supplierId),eq(suppliers.studioId,ctx.studioId),eq(suppliers.isActive,1))).limit(1))[0];if(!supplier)throw new TRPCError({code:'NOT_FOUND'});await d.insert(procurementContacts).values({studioId:ctx.studioId,supplierId:input.supplierId,confirmedBy:ctx.user.id}).onDuplicateKeyUpdate({set:{confirmedBy:ctx.user.id}});return{ok:true};}),
 defaults:tenantProcedure.mutation(async({ctx})=>{manager(ctx);const d=await database();for(const t of QUOTE_MODELS)await d.insert(procurementTemplates).values({...t,studioId:ctx.studioId}).onDuplicateKeyUpdate({set:{name:t.name}});return{ok:true};}),
 saveTemplate:tenantProcedure.input(z.object({id:z.number().optional(),name:z.string().trim().min(2).max(120),body:z.string().min(10).max(3000)})).mutation(async({ctx,input})=>{manager(ctx);const d=await database();if(input.id){const row=(await d.select().from(procurementTemplates).where(and(eq(procurementTemplates.id,input.id),eq(procurementTemplates.studioId,ctx.studioId))).limit(1))[0];if(!row)throw new TRPCError({code:'NOT_FOUND'});await d.update(procurementTemplates).set({name:input.name,body:input.body}).where(eq(procurementTemplates.id,row.id));}else await d.insert(procurementTemplates).values({studioId:ctx.studioId,name:input.name,body:input.body});return{ok:true};}),
 notification:tenantProcedure.input(z.object({materialId:z.number(),artistId:z.number().nullable(),enabled:z.boolean()})).mutation(async({ctx,input})=>{manager(ctx);const d=await database();const m=(await d.select().from(tenantMaterials).where(and(eq(tenantMaterials.id,input.materialId),eq(tenantMaterials.studioId,ctx.studioId),isNull(tenantMaterials.ownerArtistId))).limit(1))[0];if(!m)throw new TRPCError({code:'NOT_FOUND'});if(input.artistId){const supplied=(await d.select().from(studioMaterialArtists).where(and(eq(studioMaterialArtists.studioId,ctx.studioId),eq(studioMaterialArtists.tenantMaterialId,m.id),eq(studioMaterialArtists.artistId,input.artistId))).limit(1))[0];if(!supplied)throw new TRPCError({code:'BAD_REQUEST',message:'Escolha um artista ao qual este material é disponibilizado.'});await artistAccess(ctx,input.artistId);}if(input.enabled){const i=(await d.select().from(whatsappIntegrations).where(and(eq(whatsappIntegrations.studioId,ctx.studioId),eq(whatsappIntegrations.status,'ativo'),eq(whatsappIntegrations.isEnabled,1))).limit(1))[0];if(!i)throw new TRPCError({code:'BAD_REQUEST',message:'Configure e teste o WhatsApp antes de ativar avisos.'});}await d.insert(procurementAlerts).values({studioId:ctx.studioId,materialId:m.id,episode:randomUUID(),recipientArtistId:input.artistId,notifyEnabled:input.enabled?1:0}).onDuplicateKeyUpdate({set:{recipientArtistId:input.artistId,notifyEnabled:input.enabled?1:0}});return{ok:true};}),
 draft:tenantProcedure.input(z.object({materialId:z.number(),supplierId:z.number(),quantity:z.number().positive().max(999999),body:z.string().min(10).max(3000),variables:z.record(z.string().regex(/^[a-z][a-z0-9_]{0,39}$/),z.string().max(500)).refine(v=>Object.keys(v).length<=30)})).mutation(async({ctx,input})=>{manager(ctx);const d=await database();const m=(await d.select().from(tenantMaterials).where(and(eq(tenantMaterials.id,input.materialId),eq(tenantMaterials.studioId,ctx.studioId),isNull(tenantMaterials.ownerArtistId),eq(tenantMaterials.isActive,1))).limit(1))[0];const contact=(await d.select({name:suppliers.name,contactName:suppliers.contactName,phone:suppliers.phone,whatsapp:suppliers.whatsapp}).from(procurementContacts).innerJoin(suppliers,eq(suppliers.id,procurementContacts.supplierId)).where(and(eq(procurementContacts.studioId,ctx.studioId),eq(procurementContacts.supplierId,input.supplierId),eq(suppliers.studioId,ctx.studioId),eq(suppliers.isActive,1))).limit(1))[0];if(!m||!contact)throw new TRPCError({code:'BAD_REQUEST',message:'Selecione um material do estúdio e um fornecedor autorizado.'});const studio=(await d.select().from(studios).where(eq(studios.id,ctx.studioId)).limit(1))[0];const phone=normalizeBrazilianPhone(contact.whatsapp||contact.phone||'');if(!phone)throw new TRPCError({code:'BAD_REQUEST',message:'Cadastre um WhatsApp válido no fornecedor.'});const vars={...input.variables,nome_fornecedor:contact.name,primeiro_nome_fornecedor:(contact.contactName||contact.name).trim().split(/\s+/)[0],nome_estudio:studio?.name||'nosso estúdio',material:materialDescription(m),quantidade:String(input.quantity),unidade:m.unit};const rendered=renderQuote(input.body,vars);if(rendered.missing.length)throw new TRPCError({code:'BAD_REQUEST',message:'Preencha as variáveis: '+rendered.missing.join(', ')});const [result]=await d.insert(procurementQuotes).values({studioId:ctx.studioId,materialId:m.id,supplierId:input.supplierId,quantity:input.quantity.toFixed(3),recipientPhone:phone,message:rendered.message});return{id:result.insertId};}),
 approve:tenantProcedure.input(z.object({id:z.number(),message:z.string(),phone:z.string()})).mutation(async({ctx,input})=>{manager(ctx);const d=await database();const row=(await d.select().from(procurementQuotes).where(and(eq(procurementQuotes.id,input.id),eq(procurementQuotes.studioId,ctx.studioId))).limit(1))[0];if(!row||row.status!=='draft'||row.message!==input.message||row.recipientPhone!==input.phone)throw new TRPCError({code:'CONFLICT',message:'Reabra e revise o rascunho antes de aprovar.'});const integration=(await d.select().from(whatsappIntegrations).where(and(eq(whatsappIntegrations.studioId,ctx.studioId),eq(whatsappIntegrations.status,'ativo'),eq(whatsappIntegrations.isEnabled,1))).limit(1))[0];if(!integration)throw new TRPCError({code:'BAD_REQUEST',message:'Sem conexão WhatsApp ativa. O rascunho permanece salvo, sem envio.'});await d.update(procurementQuotes).set({status:'approved',approvedBy:ctx.user.id,approvedAt:stamp()}).where(and(eq(procurementQuotes.id,row.id),eq(procurementQuotes.status,'draft')));return{ok:true};}),
 cancel:tenantProcedure.input(z.object({id:z.number()})).mutation(async({ctx,input})=>{manager(ctx);await(await database()).update(procurementQuotes).set({status:'cancelled'}).where(and(eq(procurementQuotes.id,input.id),eq(procurementQuotes.studioId,ctx.studioId),eq(procurementQuotes.status,'draft')));return{ok:true};}),
});

