-- Additive inactive Intelligent Inbox scaffold. No credentials or seed data.
CREATE TABLE IF NOT EXISTS inbox_sync_state (
 id INT AUTO_INCREMENT PRIMARY KEY,
 studio_id INT NOT NULL,
 integration_id INT,
 name VARCHAR(255),
 provider VARCHAR(40) NOT NULL DEFAULT 'botconversa',
 external_id VARCHAR(255),
 status VARCHAR(40) NOT NULL DEFAULT 'not_configured',
 connected_at DATETIME,
 webhook_configured INT NOT NULL DEFAULT 0,
 sync_enabled INT NOT NULL DEFAULT 0,
 summary_enabled INT NOT NULL DEFAULT 0,
 summary_interval_minutes INT NOT NULL DEFAULT 60,
 last_sync_at DATETIME,
 last_processed_at DATETIME,
 last_message_at DATETIME,
 last_summary_at DATETIME,
 sync_status VARCHAR(40) NOT NULL DEFAULT 'disabled',
 sync_cursor TEXT,
 external_cursor TEXT,
 error_count INT NOT NULL DEFAULT 0,
 last_error TEXT,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY inbox_sync_studio_id(studio_id,id),
 KEY inbox_sync_connection(studio_id,integration_id)
);
CREATE TABLE IF NOT EXISTS inbox_conversations (
 id INT AUTO_INCREMENT PRIMARY KEY,
 studio_id INT NOT NULL,
 sync_state_id INT NOT NULL,
 client_id INT,
 integration_contact_id INT,
 external_contact_id VARCHAR(255),
 external_conversation_id VARCHAR(191) NOT NULL,
 client_name VARCHAR(255),
 phone VARCHAR(32),
 source VARCHAR(80),
 channel VARCHAR(80),
 artist_id INT,
 attendant_user_id INT,
 last_interaction_at DATETIME,
 status VARCHAR(40) NOT NULL DEFAULT 'open',
 priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
 classification VARCHAR(80) NOT NULL DEFAULT 'other',
 waiting_since DATETIME,
 waiting_seconds INT NOT NULL DEFAULT 0,
 summary TEXT,
 purchase_intent VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
 pending_actions TEXT,
 next_recommended_action TEXT,
 suggested_reply TEXT,
 analyzed_message_count INT NOT NULL DEFAULT 0,
 last_summary_at DATETIME,
 last_processed_at DATETIME,
 processing_status VARCHAR(40) NOT NULL DEFAULT 'disabled',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY inbox_conversation_studio_id(studio_id,id),
 UNIQUE KEY inbox_conversation_external(studio_id,sync_state_id,external_conversation_id),
 KEY inbox_conversation_activity(studio_id,last_interaction_at,id),
 KEY inbox_conversation_priority(studio_id,status,priority,id),
 KEY inbox_conversation_classification(studio_id,classification,id),
 KEY inbox_conversation_client(studio_id,client_id,id),
 KEY inbox_conversation_artist(studio_id,artist_id,id),
 KEY inbox_conversation_attendant(studio_id,attendant_user_id,id),
 KEY inbox_conversation_phone(studio_id,phone),
 CONSTRAINT inbox_conversation_sync_fk FOREIGN KEY (studio_id,sync_state_id) REFERENCES inbox_sync_state(studio_id,id)
);
CREATE TABLE IF NOT EXISTS inbox_messages (
 id INT AUTO_INCREMENT PRIMARY KEY,
 studio_id INT NOT NULL,
 conversation_id INT NOT NULL,
 external_message_id VARCHAR(191) NOT NULL,
 message_type VARCHAR(40) NOT NULL DEFAULT 'text',
 direction VARCHAR(20) NOT NULL DEFAULT 'inbound',
 actor VARCHAR(40) NOT NULL DEFAULT 'customer',
 text_content TEXT,
 media_reference TEXT,
 metadata TEXT,
 message_at DATETIME,
 processed_at DATETIME,
 processing_status VARCHAR(40) NOT NULL DEFAULT 'disabled',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY inbox_message_external(studio_id,conversation_id,external_message_id),
 KEY inbox_message_page(studio_id,conversation_id,message_at,id),
 KEY inbox_message_pending(studio_id,processing_status,id),
 CONSTRAINT inbox_messages_conversation_fk FOREIGN KEY (studio_id,conversation_id) REFERENCES inbox_conversations(studio_id,id)
);
CREATE TABLE IF NOT EXISTS inbox_summaries (
 id INT AUTO_INCREMENT PRIMARY KEY,
 studio_id INT NOT NULL,
 conversation_id INT,
 scope_key VARCHAR(100) NOT NULL,
 window_start DATETIME NOT NULL,
 window_end DATETIME NOT NULL,
 summary TEXT,
 metrics TEXT,
 analysis TEXT,
 analyzed_message_count INT NOT NULL DEFAULT 0,
 last_message_id INT,
 processing_status VARCHAR(40) NOT NULL DEFAULT 'disabled',
 analysis_version VARCHAR(80),
 last_error TEXT,
 processed_at DATETIME,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY inbox_summary_window(studio_id,scope_key,window_start,window_end),
 KEY inbox_summary_history(studio_id,window_end,id),
 KEY inbox_summary_conversation(studio_id,conversation_id,id),
 CONSTRAINT inbox_summaries_conversation_fk FOREIGN KEY (studio_id,conversation_id) REFERENCES inbox_conversations(studio_id,id)
);
ALTER TABLE user_module_permissions MODIFY COLUMN module ENUM('clients','appointments','stock','finance','anamnesis','pod','reports','intelligent_inbox','inbox_conversations','inbox_summaries','inbox_priorities','inbox_opportunities','inbox_settings','inbox_suggestions') NOT NULL;
