CREATE TABLE IF NOT EXISTS `procedure_color_samples` (
  `id` int AUTO_INCREMENT NOT NULL,
  `studioId` int NOT NULL,
  `procedureId` int NOT NULL,
  `clientId` int NOT NULL,
  `artistId` int,
  `code` varchar(16) NOT NULL,
  `hex` varchar(9) NOT NULL,
  `red` int NOT NULL,
  `green` int NOT NULL,
  `blue` int NOT NULL,
  `cyan` int NOT NULL,
  `magenta` int NOT NULL,
  `yellow` int NOT NULL,
  `black` int NOT NULL,
  `labL` decimal(7,3),
  `labA` decimal(7,3),
  `labB` decimal(7,3),
  `xPct` decimal(7,4) NOT NULL,
  `yPct` decimal(7,4) NOT NULL,
  `sampleSize` int NOT NULL DEFAULT 5,
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `procedure_color_samples_id` PRIMARY KEY(`id`),
  CONSTRAINT `procedure_color_sample_code_unique` UNIQUE(`studioId`,`procedureId`,`code`),
  INDEX `procedure_color_samples_procedure_idx`(`studioId`,`procedureId`,`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `procedure_ink_recipes` (
  `id` int AUTO_INCREMENT NOT NULL,
  `studioId` int NOT NULL,
  `procedureId` int NOT NULL,
  `clientId` int NOT NULL,
  `artistId` int,
  `sampleId` int,
  `code` varchar(16) NOT NULL,
  `cupSize` varchar(8) NOT NULL,
  `cupCapacityMl` decimal(8,3) NOT NULL,
  `dropsPerMl` decimal(8,3) NOT NULL,
  `totalDrops` int NOT NULL,
  `estimatedMl` decimal(8,3) NOT NULL,
  `cupTenantMaterialId` int,
  `cupConsumptionId` int,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `createdByUserId` int NOT NULL,
  `revertedAt` datetime,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `procedure_ink_recipes_id` PRIMARY KEY(`id`),
  CONSTRAINT `procedure_ink_recipe_code_unique` UNIQUE(`studioId`,`procedureId`,`code`),
  INDEX `procedure_ink_recipes_procedure_idx`(`studioId`,`procedureId`,`id`),
  INDEX `procedure_ink_recipes_sample_idx`(`studioId`,`sampleId`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `procedure_ink_recipe_items` (
  `id` int AUTO_INCREMENT NOT NULL,
  `studioId` int NOT NULL,
  `recipeId` int NOT NULL,
  `tenantMaterialId` int NOT NULL,
  `consumptionId` int NOT NULL,
  `batchId` int,
  `nameSnapshot` varchar(255) NOT NULL,
  `brandSnapshot` varchar(120),
  `lotSnapshot` varchar(120),
  `expiresAtSnapshot` datetime,
  `drops` int NOT NULL,
  `estimatedMl` decimal(8,3) NOT NULL,
  `percentage` decimal(7,3) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `procedure_ink_recipe_items_id` PRIMARY KEY(`id`),
  INDEX `procedure_ink_recipe_items_recipe_idx`(`studioId`,`recipeId`,`id`),
  INDEX `procedure_ink_recipe_items_consumption_idx`(`studioId`,`consumptionId`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `tenant_material_color_samples` (
  `id` int AUTO_INCREMENT NOT NULL,
  `studioId` int NOT NULL,
  `tenantMaterialId` int NOT NULL,
  `artistId` int,
  `source` varchar(24) NOT NULL DEFAULT 'photo',
  `hex` varchar(9) NOT NULL,
  `red` int NOT NULL,
  `green` int NOT NULL,
  `blue` int NOT NULL,
  `cyan` int NOT NULL,
  `magenta` int NOT NULL,
  `yellow` int NOT NULL,
  `black` int NOT NULL,
  `labL` decimal(7,3) NOT NULL,
  `labA` decimal(7,3) NOT NULL,
  `labB` decimal(7,3) NOT NULL,
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `tenant_material_color_samples_id` PRIMARY KEY(`id`),
  CONSTRAINT `tenant_material_color_sample_unique` UNIQUE(`studioId`,`tenantMaterialId`),
  INDEX `tenant_material_color_samples_artist_idx`(`studioId`,`artistId`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `procedure_ink_recipe_results` (
  `id` int AUTO_INCREMENT NOT NULL,
  `studioId` int NOT NULL,
  `recipeId` int NOT NULL,
  `procedureId` int NOT NULL,
  `clientId` int NOT NULL,
  `artistId` int,
  `hex` varchar(9) NOT NULL,
  `red` int NOT NULL,
  `green` int NOT NULL,
  `blue` int NOT NULL,
  `cyan` int NOT NULL,
  `magenta` int NOT NULL,
  `yellow` int NOT NULL,
  `black` int NOT NULL,
  `labL` decimal(7,3) NOT NULL,
  `labA` decimal(7,3) NOT NULL,
  `labB` decimal(7,3) NOT NULL,
  `note` varchar(500),
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `procedure_ink_recipe_results_id` PRIMARY KEY(`id`),
  CONSTRAINT `procedure_ink_recipe_result_unique` UNIQUE(`studioId`,`recipeId`),
  INDEX `procedure_ink_recipe_results_artist_idx`(`studioId`,`artistId`,`id`),
  INDEX `procedure_ink_recipe_results_procedure_idx`(`studioId`,`procedureId`,`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `procedure_visual_layers` (
  `id` int AUTO_INCREMENT NOT NULL,
  `studioId` int NOT NULL,
  `procedureId` int NOT NULL,
  `clientId` int NOT NULL,
  `artistId` int,
  `layerKey` varchar(80) NOT NULL,
  `name` varchar(160) NOT NULL,
  `layerType` varchar(32) NOT NULL,
  `imageUrl` varchar(3000),
  `imageKey` varchar(500),
  `opacity` int NOT NULL DEFAULT 100,
  `isVisible` int NOT NULL DEFAULT 1,
  `sortOrder` int NOT NULL DEFAULT 0,
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `procedure_visual_layers_id` PRIMARY KEY(`id`),
  CONSTRAINT `procedure_visual_layer_key_unique` UNIQUE(`studioId`,`procedureId`,`layerKey`),
  INDEX `procedure_visual_layers_order_idx`(`studioId`,`procedureId`,`sortOrder`,`id`)
);
