/** One-off demo content for the dedicated test service; never production. */
import assert from 'node:assert/strict';
import {brotliDecompressSync} from 'node:zlib';
import {createHash} from 'node:crypto';
const BASE='https://cartao-artista-teste-staging-custos.up.railway.app';
assert.equal(process.env.ARTIST_CARD_TEST_ENV,'true');assert.equal(process.env.APP_BASE_URL,BASE);assert.equal(new URL(process.env.DATABASE_URL).pathname,'/artist_card_test_20260919');assert.equal(process.env.OUTBOUND_MESSAGING_DISABLED,'true');assert.equal(process.env.LOCAL_ADMIN_EMAIL,'teste.cartao@example.com');assert.equal(process.env.RAILWAY_SERVICE_ID,'e834a3ac-1180-4ba3-b0c6-e9f07a20ddd6');
const login=await fetch(BASE+'/api/auth/local/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:process.env.LOCAL_ADMIN_EMAIL,password:process.env.LOCAL_ADMIN_PASSWORD}),signal:AbortSignal.timeout(20000)});assert.equal(login.status,200);
const cookie=login.headers.getSetCookie().map(h=>h.split(';')[0]).join('; ');assert.ok(cookie);
async function rpc(name,input={},mutation=false,auth=true){const data=JSON.stringify({json:input});const r=await fetch(BASE+'/api/trpc/'+name+(mutation?'':'?input='+encodeURIComponent(data)),{method:mutation?'POST':'GET',headers:{'Content-Type':'application/json',...(auth?{Cookie:cookie}:{})},...(mutation?{body:data}:{}),signal:AbortSignal.timeout(30000)});const e=await r.json();if(e.error)throw new Error(name+': '+(e.error.json||e.error).message);assert.ok(r.ok);return e.result.data?.json??e.result.data;}
const NAME='Artista Demonstração';const MARK='[EDITORIAL_DEMO_20260919]';let rows=await rpc('artists.list');let a=rows.find(x=>x.name===NAME);
if(!a){await rpc('artists.create',{name:NAME,email:'',phone:'',instagram:'',specialty:'Perfil demonstrativo',bio:MARK+' Fotografias e informações demonstrativas. Nenhuma identidade ou credencial real.',photoUrl:'',color:'#F97316',active:1},true);rows=await rpc('artists.list');a=rows.find(x=>x.name===NAME);}
assert.ok(a?.id);assert.ok(a.bio?.startsWith(MARK),'Existing artist is not this controlled demo');
let card=await rpc('studioRelations.card',{artistId:a.id});
if(card?.published===1&&card.images.length>=5&&card.presentation?.cover&&card.presentation?.about&&card.presentation?.process){console.log('[ArtistCardDemo] Existing complete demo preserved');console.log('[ArtistCardDemo] PUBLIC_CARD '+BASE+'/artista/'+card.token);process.exit(0);}
const source='https://raw.githubusercontent.com/Boludodismo/pulse-com/refs/heads/preview/artist-card-editorial-2026-09-19/previews/artist-card-online/';const pieces=[];
for(const n of [1,2,3]){const r=await fetch(source+`page.${n}.brpart`,{signal:AbortSignal.timeout(20000)});assert.ok(r.ok,'Approved reference data unavailable');pieces.push(Buffer.from(await r.arrayBuffer()));}
const html=brotliDecompressSync(Buffer.concat(pieces));assert.equal(createHash('sha256').update(html).digest('hex'),'f1c733770f8de84e224762bc93c9b8a1fd8ac0577cd4dd8cc775cee3ce72ce8d','Reference integrity mismatch');
const s=html.toString('utf8'),marker='const DEMO_DATA=',start=s.indexOf(marker)+marker.length,end=s.indexOf(';</script>',start);assert.ok(start>marker.length&&end>start);const demo=JSON.parse(s.slice(start,end));
console.log('[ArtistCardDemo] Approved demonstration image data verified; no reference script executed');
const form={artistId:a.id,headline:'Artista visual / apresentação demonstrativa',description:'Este é um perfil demonstrativo para você testar o novo cartão de apresentação. As fotografias e os trabalhos são exemplos visuais, não representam a identidade ou o portfólio de um artista cadastrado.\n\nCada profissional poderá preencher a própria biografia, indicar sua formação, inserir suas fotografias e informar as redes sociais. A organização visual será mantida pelo sistema.',links:[{label:'Instagram',url:'https://www.instagram.com/'},{label:'Portfólio demonstrativo',url:'https://example.com/'}],published:false,presentation:{tagline:'Sua identidade.\nSua técnica. Sua expressão.',quote:'Uma visão autoral.\nUma presença marcante.',specialties:'Especialidades informadas pelo profissional.',techniques:'Técnicas e linguagens utilizadas em seus trabalhos.',education:'Formação, cursos e aperfeiçoamentos que o artista desejar divulgar.',experience:'Experiência descrita pelo próprio profissional, sem números automáticos.',location:'Cidade e espaço de atuação informados pelo artista.'}};
await rpc('studioRelations.saveCard',form,true);card=await rpc('studioRelations.card',{artistId:a.id});
for(const slot of ['cover','about','process']){if(!card.presentation?.[slot]){const m=demo.presentation[slot];assert.ok(m.url.startsWith('data:image/jpeg;base64,'));await rpc('studioRelations.uploadPresentationMedia',{artistId:a.id,slot,alt:m.alt||'Imagem demonstrativa',imageBase64:m.url,mimeType:'image/jpeg',x:m.x??50,y:m.y??50},true);}}
for(let i=card.images.length;i<5;i++){assert.ok(demo.images[i].url.startsWith('data:image/jpeg;base64,'));await rpc('studioRelations.uploadWork',{artistId:a.id,caption:'Trabalho demonstrativo '+(i+1),imageBase64:demo.images[i].url,mimeType:'image/jpeg'},true);}
await rpc('studioRelations.saveCard',{...form,published:true},true);card=await rpc('studioRelations.card',{artistId:a.id});const publicCard=await rpc('studioRelations.publicCard',{token:card.token},false,false);assert.equal(publicCard.images.length,5);assert.ok(publicCard.presentation.cover&&publicCard.presentation.about&&publicCard.presentation.process);
for(const m of [publicCard.presentation.cover,publicCard.presentation.about,publicCard.presentation.process,...publicCard.images]){const r=await fetch(new URL(m.url,BASE),{signal:AbortSignal.timeout(20000)});assert.equal(r.status,200);assert.match(r.headers.get('content-type')||'',/^image\//);assert.ok((await r.arrayBuffer()).byteLength>1000);}
console.log('[ArtistCardDemo] COMPLETE: one fictional artist, three photos, five works, persisted content and readable images');console.log('[ArtistCardDemo] PUBLIC_CARD '+BASE+'/artista/'+card.token);
