/** Only a disposable local CI database; never production or customer records. */
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import mysql from "mysql2/promise";
import { router } from "../server/_core/trpc";
import { podSaasRouter } from "../server/routers/podSaas";
import { proceduresRouter } from "../server/routers/procedures";
import { ensureSessionCockpitSchema } from "../server/_core/sessionCockpitSchema";
import { upgradeInventoryTrace } from "../server/_core/inventoryTraceSchema";
import { upgradeInventoryWorkflow } from "../server/_core/inventoryWorkflowSchema";
import { upgradeAppointmentKits } from "../server/_core/appointmentKitSchema";
import { ensureStudioSettingsScope } from "../server/_core/studioSettingsScope";
import { visualLayerStack } from "../shared/sessionVisualLayers";
import { emptyPreparation } from "../shared/sessionPreparation";

async function main() {
  const url = new URL(process.env.DATABASE_URL!);
  assert.equal(process.env.CI, "true");
  assert.ok(["127.0.0.1", "localhost"].includes(url.hostname));
  assert.equal(url.pathname, "/supplier_test");
  const db = await mysql.createConnection({ uri: url.toString(), dateStrings: true });
  await upgradeInventoryTrace(db); await upgradeInventoryWorkflow(db); await upgradeAppointmentKits(db);
  await ensureSessionCockpitSchema(); await ensureSessionCockpitSchema();
  await ensureStudioSettingsScope();
  await db.query("INSERT INTO artists(id,studioId,name,active) VALUES(9101,101,'Artista de teste',1)");
  await db.query("INSERT INTO clients(id,studioId,name) VALUES(9101,101,'Cliente de teste')");
  const root = router({ pod: podSaasRouter, procedures: proceduresRouter });
  const ctx = { user: { id: 101, studioId: 101, openId: "test", role: "admin", isActive: 1, accessStatus: "active" }, req: { headers: {} }, res: {} };
  const api = root.createCaller(ctx as any);
  const other = root.createCaller({ ...ctx, user: { ...ctx.user, studioId: 202 } } as any);
  const createMaterial = (name: string, unit: string, category: string) => api.pod.inventory.create({ name, unit, category, ownerArtistId: 9101, currentQuantity: "100", unitCost: "2" });
  const vaseline = await createMaterial("Vaselina Electric Ink Slip Premium", "g", "Cosméticos");
  const black = await createMaterial("Tinta preta", "ml", "Tintas");
  const gray = await createMaterial("Tinta cinza", "ml", "Tintas");
  const diluent = await createMaterial("Diluente", "ml", "Diluente");
  const cup = await createMaterial("Batoque P", "un", "Batoques");
  await assert.rejects(createMaterial("Vaselina inválida", "gotas", "Cosméticos"));
  const preparation = { ...emptyPreparation(), materials: [{ tenantMaterialId: vaseline.id, name: "Vaselina", unit: "g", quantity: "20.000" }, { tenantMaterialId: cup.id, name: "Batoque P", unit: "un", quantity: "2" }] };
  const input = { clientId: 9101, artistId: 9101, title: "Sessão isolada", requestId: randomUUID(), preparation };
  const created = await api.procedures.create(input);
  assert.equal((await api.procedures.create(input)).id, created.id);
  await api.procedures.timerAction({ id: created.id, action: "start" });
  const session = await api.pod.session.get({ procedureId: created.id });
  assert.deepEqual(session.sessionMaterials.map(m => [m.tenantMaterialId, m.quantity]), [[vaseline.id, "20.000"], [cup.id, "2"]]);
  assert.equal(session.consumptions.length, 0);
  const stock = async (id: number) => Number((await api.pod.inventory.list({ artistId: 9101 })).find(m => m.id === id)!.currentQuantity);
  assert.equal(await stock(vaseline.id), 100);
  await Promise.all([1, 2].map(() => api.pod.session.addMaterial({ procedureId: created.id, tenantMaterialId: diluent.id })));
  assert.equal((await api.pod.session.get({ procedureId: created.id })).sessionMaterials.filter(m => m.tenantMaterialId === diluent.id).length, 1);
  assert.equal(await stock(diluent.id), 100);
  const consume = { procedureId: created.id, tenantMaterialId: vaseline.id, quantity: "20.000", requestId: randomUUID() };
  const results = await Promise.all([api.pod.session.consumeAuto(consume), api.pod.session.consumeAuto(consume)]);
  assert.equal(results[0].id, results[1].id);
  assert.equal(await stock(vaseline.id), 80);
  await assert.rejects(api.pod.session.consumeAuto({ ...consume, quantity: "21" }));
  await assert.rejects(other.pod.session.consumeAuto({ ...consume, requestId: randomUUID() }));
  await api.pod.session.revertConsumption({ consumptionId: results[0].id, reason: "Teste de reversão" });
  await api.pod.session.revertConsumption({ consumptionId: results[0].id, reason: "Repetição" });
  assert.equal(await stock(vaseline.id), 100);
  const independent = await api.pod.session.consumeAuto({ procedureId: created.id, tenantMaterialId: diluent.id, quantity: "0.050", requestId: randomUUID() });
  assert.equal(await stock(diluent.id), 99.95);
  await api.pod.session.revertConsumption({ consumptionId: independent.id, reason: "Teste" });
  const recipeInput = { procedureId: created.id, requestId: randomUUID(), cupSize: null, dropsPerMl: 20, ingredients: [{ tenantMaterialId: black.id, drops: 4 }, { tenantMaterialId: gray.id, drops: 2 }, { tenantMaterialId: diluent.id, drops: 1 }] };
  const recipes = await Promise.all([api.pod.session.saveInkRecipe(recipeInput), api.pod.session.saveInkRecipe(recipeInput)]);
  assert.equal(recipes[0].id, recipes[1].id);
  assert.equal(recipes[0].cupConsumptionId, null);
  assert.equal(await stock(black.id), 99.8);
  assert.equal(await stock(gray.id), 99.9);
  assert.equal(await stock(diluent.id), 99.95);
  assert.equal(await stock(cup.id), 100);
  await api.pod.session.revertInkRecipe({ recipeId: recipes[0].id, reason: "Teste" });
  await api.pod.session.revertInkRecipe({ recipeId: recipes[0].id, reason: "Repetição" });
  assert.equal(await stock(black.id), 100); assert.equal(await stock(diluent.id), 100);
  const withCup = await api.pod.session.saveInkRecipe({ ...recipeInput, requestId: randomUUID(), cupSize: "P", cupTenantMaterialId: cup.id });
  assert.equal(await stock(cup.id), 99);
  await assert.rejects(api.pod.session.saveInkRecipe({ ...recipeInput, requestId: randomUUID(), cupSize: "G", cupTenantMaterialId: cup.id }));
  await assert.rejects(api.pod.session.saveInkRecipe({ ...recipeInput, requestId: randomUUID(), cupSize: "P", ingredients: [{ tenantMaterialId: black.id, drops: 11 }] }));
  assert.equal(await stock(cup.id), 99);
  await api.pod.session.revertInkRecipe({ recipeId: withCup.id, reason: "Teste" });
  const cartridge = await createMaterial("Cartucho Electric Ink 1009MGL", "un", "Cartuchos e agulhas");
  await api.pod.session.addMaterial({procedureId:created.id,tenantMaterialId:cartridge.id});
  assert.equal(await stock(cartridge.id),100);
  await assert.rejects(api.pod.session.consumeAuto({procedureId:created.id,tenantMaterialId:cartridge.id,quantity:"0.5"}));
  const cartridgeInput={procedureId:created.id,tenantMaterialId:cartridge.id,quantity:"3",expectedUnit:"un",requestId:randomUUID()};
  const c=await api.pod.session.consumeAuto(cartridgeInput);
  await api.pod.session.consumeAuto(cartridgeInput);
  assert.equal(await stock(cartridge.id),97);
  const audit=(await api.pod.session.get({procedureId:created.id})).consumptions.find(row=>row.id===c.id)!;
  assert.equal(audit.unitSnapshot,"un");assert.equal(Number(audit.totalCostSnapshot),6);
  const summary=await api.procedures.getSummary({id:created.id});
  assert.ok(summary.confirmedInventoryCost>=6);
  assert.equal(summary.inventoryConsumptions.find(row=>row.id===c.id)?.unitSnapshot,"un");
  assert.equal(audit.clientId,9101);assert.equal(audit.tenantMaterialId,cartridge.id);
  await api.pod.session.revertConsumption({consumptionId:c.id,reason:"Teste de unidade"});
  assert.equal(await stock(cartridge.id),100);
  const afterReversal=await api.procedures.getSummary({id:created.id});
  assert.equal(Number((summary.totalMaterialCost-afterReversal.totalMaterialCost).toFixed(4)),6);
  await assert.rejects(createMaterial("Cartucho incorreto", "g", "Cartuchos"));
  console.log("PASS: persisted selection, quantities, start without consumption, explicit additions, independent diluent, recipes, stock, concurrent retries, rollback and reversal");

  // Layer composition settings must survive reads and be isolated from stock and other tenants.
  const layers = () => api.pod.session.listVisualLayers({procedureId:created.id});
  const order = async () => visualLayerStack(await layers()).map(layer=>layer.layerKey);
  const beforeStock = await stock(vaseline.id);
  const baseOrder = await order();
  assert.deepEqual(baseOrder,["samples","reference"]);
  const layerA = await api.pod.session.addVisualLayer({procedureId:created.id,name:"Arte teste A",layerType:"image",imageUrl:"/test-layer-a.png",imageKey:"test-layer-a",opacity:60});
  const layerB = await api.pod.session.addVisualLayer({procedureId:created.id,name:"Arte teste B",layerType:"stencil_overlay",imageUrl:"/test-layer-b.png",imageKey:"test-layer-b",opacity:40});
  await api.pod.session.updateVisualLayer({procedureId:created.id,layerKey:layerA.layerKey,opacity:37,isVisible:false});
  const expectedKeys = await order();
  const orderedKeys = ["reference",layerA.layerKey,"samples",layerB.layerKey];
  await api.pod.session.reorderVisualLayers({procedureId:created.id,expectedKeys,orderedKeys});
  assert.deepEqual(await order(),orderedKeys);
  const savedA=(await layers()).find(layer=>layer.layerKey===layerA.layerKey)!;
  assert.equal(savedA.opacity,37); assert.equal(savedA.isVisible,0); assert.equal(savedA.imageUrl,"/test-layer-a.png");
  await assert.rejects(api.pod.session.reorderVisualLayers({procedureId:created.id,expectedKeys,orderedKeys:expectedKeys}));
  await assert.rejects(api.pod.session.reorderVisualLayers({procedureId:created.id,expectedKeys:orderedKeys,orderedKeys:["reference",layerA.layerKey,"samples","foreign-layer"]}));
  await assert.rejects(api.pod.session.reorderVisualLayers({procedureId:created.id,expectedKeys:orderedKeys,orderedKeys:["reference",layerA.layerKey,"samples","samples"]}));
  await assert.rejects(other.pod.session.reorderVisualLayers({procedureId:created.id,expectedKeys:orderedKeys,orderedKeys:[...orderedKeys].reverse()}));
  await assert.rejects(other.pod.session.updateVisualLayer({procedureId:created.id,layerKey:layerA.layerKey,opacity:12}));
  await assert.rejects(api.pod.session.updateVisualLayer({procedureId:created.id,layerKey:layerA.layerKey,opacity:101}));
  assert.deepEqual(await order(),orderedKeys);
  const competing=await Promise.allSettled([
    api.pod.session.reorderVisualLayers({procedureId:created.id,expectedKeys:orderedKeys,orderedKeys:[...orderedKeys].reverse()}),
    api.pod.session.reorderVisualLayers({procedureId:created.id,expectedKeys:orderedKeys,orderedKeys:[orderedKeys[1],orderedKeys[0],orderedKeys[2],orderedKeys[3]]}),
  ]);
  assert.equal(competing.filter(result=>result.status==="fulfilled").length,1);
  assert.equal(competing.filter(result=>result.status==="rejected").length,1);
  await api.pod.session.updateVisualLayer({procedureId:created.id,layerKey:"reference",opacity:0,isVisible:false});
  await api.pod.session.updateVisualLayer({procedureId:created.id,layerKey:"reference",isVisible:true});
  assert.equal((await layers()).find(layer=>layer.layerKey==="reference")!.opacity,0);
  await db.query("UPDATE procedure_visual_layers SET imageKey=NULL WHERE procedureId=? AND layerKey=?",[created.id,layerB.layerKey]);
  const beforeRemove=await order();
  await api.pod.session.removeVisualLayer({procedureId:created.id,layerKey:layerB.layerKey});
  await assert.rejects(api.pod.session.reorderVisualLayers({procedureId:created.id,expectedKeys:beforeRemove,orderedKeys:[...beforeRemove].reverse()}));
  assert.ok(!(await order()).includes(layerB.layerKey));
  assert.equal(await stock(vaseline.id),beforeStock);
  console.log("PASS: layer order, opacity, visibility, atomic concurrent reorder, stale/deleted/foreign layers, bounds and tenant isolation");

  await db.end();
}
main().then(() => process.exit(0)).catch(error => { console.error(error); process.exit(1); });
