import {normalizeCardLinks} from '../../../shared/studioRelations';
import {useState,useEffect,useRef} from 'react';
import {trpc} from '@/lib/trpc';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from './ui/dialog';
import {toast} from 'sonner';
export default function ArtistCardEditor({artistId,name}:{artistId:number,name:string}){
 const [open,setOpen]=useState(false);const utils=trpc.useUtils();const q=trpc.studioRelations.card.useQuery({artistId},{enabled:open});const [form,setForm]=useState({headline:'',description:'',published:false,links:[] as {label:string,url:string}[]});const [caption,setCaption]=useState('');const [uploading,setUploading]=useState(false);
 const initialized=useRef(false);
 useEffect(()=>{if(!open){initialized.current=false;return;}if(q.isLoading||q.error||initialized.current)return;initialized.current=true;if(q.data)setForm({headline:q.data.headline,description:q.data.description,published:!!q.data.published,links:q.data.links});else setForm({headline:'',description:'',published:false,links:[]});},[open,q.isLoading,q.error,q.data]);
 const refresh=()=>utils.studioRelations.card.invalidate({artistId});
 const save=trpc.studioRelations.saveCard.useMutation({onSuccess:()=>{refresh();toast.success('Cartão salvo.');},onError:e=>toast.error(e.message)});
 const upload=trpc.studioRelations.uploadWork.useMutation({onSuccess:()=>{refresh();setCaption('');toast.success('Trabalho salvo no portfólio.');},onError:e=>toast.error(e.message)});
 const remove=trpc.studioRelations.removeWork.useMutation({onSuccess:refresh,onError:e=>toast.error(e.message)});
 return <><Button size="sm" variant="outline" onClick={e=>{e.stopPropagation();setOpen(true);}}>Cartão virtual</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent onClick={e=>e.stopPropagation()} className="max-h-[90dvh] overflow-y-auto max-w-xl"><DialogHeader><DialogTitle>Cartão virtual · {name}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Somente nome, avatar, apresentação, redes e trabalhos deste cartão serão públicos. O cartão publicado será incluído na confirmação do atendimento.</p>{q.error?<p role="alert">Não foi possível carregar o cartão.</p>:q.isLoading?<p>Carregando…</p>:<>
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();try{const links=normalizeCardLinks(form.links);setForm({...form,links});save.mutate({artistId,...form,links});}catch(error){toast.error((error as Error).message);}}}><label className="block">Título / especialidade<Input maxLength={160} value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})}/></label><label className="block">Apresentação<Textarea value={form.description} maxLength={3000} onChange={e=>setForm({...form,description:e.target.value})}/></label><h3>Redes sociais e links</h3>{form.links.map((l,i)=><div className="grid gap-2 sm:grid-cols-[1fr_2fr_auto] rounded-lg border p-3" key={i}><label className="min-w-0 text-sm">Nome da rede (opcional)<Input maxLength={40} aria-label={`Nome da rede ${i+1}`} placeholder="Preenchido a partir do link" value={l.label} onChange={e=>setForm({...form,links:form.links.map((x,j)=>j===i?{...x,label:e.target.value}:x)})}/></label><label className="min-w-0 text-sm">Link completo<Input aria-label={`URL da rede ${i+1}`} placeholder="https://www.instagram.com/seuusuario" maxLength={500} type="text" inputMode="url" value={l.url} onChange={e=>setForm({...form,links:form.links.map((x,j)=>j===i?{...x,url:e.target.value}:x)})}/></label><Button type="button" variant="outline" onClick={()=>setForm({...form,links:form.links.filter((_,j)=>j!==i)})}>Remover</Button></div>)}<Button type="button" variant="outline" disabled={form.links.length>=8} onClick={()=>setForm({...form,links:[...form.links,{label:'',url:''}]})}>Adicionar rede social</Button><label className="flex gap-2"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/>Publicar cartão e incluir nas confirmações</label><Button disabled={save.isPending||uploading||upload.isPending}>Salvar cartão</Button></form>
 {q.data?.published===1&&<a className="underline break-all" target="_blank" rel="noreferrer" href={`/artista/${q.data.token}`}>Abrir cartão público</a>}
 <h3 className="font-semibold">Portfólio · até 12 trabalhos</h3><p className="text-sm">Envie somente imagens autorizadas para divulgação. JPG, PNG ou WebP de até 5 MB.</p><p className="text-sm text-muted-foreground">Você já pode adicionar imagens. Elas são salvas ao enviar; use Salvar cartão para guardar os textos e publicar.</p><><Input aria-label="Legenda do trabalho" placeholder="Legenda do trabalho" value={caption} maxLength={160} onChange={e=>setCaption(e.target.value)}/><Input aria-label="Enviar imagem do portfólio" type="file" accept="image/jpeg,image/png,image/webp" disabled={save.isPending||uploading||upload.isPending||(q.data?.images.length||0)>=12} onChange={async e=>{const input=e.currentTarget;const file=input.files?.[0];if(!file)return;if(file.size>5*1024*1024){toast.error('Limite de 5 MB.');return;}setUploading(true);try{const imageBase64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});await upload.mutateAsync({artistId,caption,imageBase64,mimeType:file.type as any});}catch(error){if(!(error instanceof Error)||!('data' in error))toast.error('Não foi possível enviar a imagem. Tente novamente.');}finally{setUploading(false);input.value='';}}}/><div className="grid grid-cols-2 gap-3">{q.data?.images.map(img=><figure key={img.key}><img src={img.url} alt={img.caption||'Trabalho do artista'} className="rounded-lg w-full aspect-square object-cover"/><figcaption>{img.caption}</figcaption><Button size="sm" variant="outline" disabled={remove.isPending} onClick={()=>remove.mutate({artistId,key:img.key})}>Retirar do cartão</Button></figure>)}</div></>
 </>}</DialogContent></Dialog></>;
}
