import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from './ui/dialog';
export default function ConsumeMaterialBatch({material,artistId,initialQuantity,busy,onClose,onConfirm}:{material:{id:number;name:string;unit:string;currentQuantity:string};artistId?:number;initialQuantity:string;busy:boolean;onClose:()=>void;onConfirm:(quantity:string,batchId?:number)=>void}){
 const [batch,setBatch]=useState('');const [quantity,setQuantity]=useState(initialQuantity);
 const batches=trpc.pod.inventory.batches.useQuery({tenantMaterialId:material.id,artistId});const legacy=Number(material.currentQuantity)-(batches.data??[]).reduce((n,b)=>n+Number(b.remainingQuantity),0);
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date());
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent><DialogHeader><DialogTitle>Utilizar {material.name}</DialogTitle></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();onConfirm(quantity.replace(',','.'),batch==='legacy'?undefined:Number(batch))}}><label className="block">Lote utilizado<select required className="block w-full border rounded bg-background p-2" value={batch} onChange={e=>setBatch(e.target.value)}><option value="">Selecione o lote da embalagem</option>{batches.data?.filter(b=>Number(b.remainingQuantity)>0).map(b=><option key={b.id} value={b.id} disabled={!!b.expiresAt&&b.expiresAt.slice(0,10)<today}>{b.lot} · {b.supplierName} · saldo {b.remainingQuantity} · validade {b.expiresAt?b.expiresAt.slice(0,10).split('-').reverse().join('/'):'não informada'}{b.expiresAt&&b.expiresAt.slice(0,10)<today?' — vencido':''}</option>)}{legacy>0&&<option value="legacy">Saldo anterior sem lote recebido · {legacy.toFixed(3)} {material.unit}</option>}</select></label>{batch==='legacy'&&<p className="text-sm text-amber-500">Este saldo não possui recebimento rastreável. O histórico manterá apenas os dados antigos disponíveis, sem inventar fornecedor ou lote.</p>}{batches.error&&<p role="alert">{batches.error.message}</p>}<label className="block">Quantidade utilizada ({material.unit})<Input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><Button disabled={!batch||busy||batches.isLoading||!!batches.error}>{busy?'Registrando…':'Confirmar consumo deste lote'}</Button></form></DialogContent></Dialog>;
}
