import {materialDescription} from "@shared/materialDescription";
import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {useAuth} from '@/_core/hooks/useAuth';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from './ui/dialog';
import {toast} from 'sonner';
import {QUOTE_VARIABLES} from '../../../shared/studioRelations';
export function AuthorizeQuoteSupplier({supplierId}:{supplierId:number}){const {user}=useAuth();const m=trpc.studioRelations.authorizeSupplier.useMutation({onSuccess:()=>toast.success('Fornecedor habilitado para preparar orçamentos deste estúdio. Nenhuma mensagem enviada.'),onError:e=>toast.error(e.message)});return user?.role==='admin'||user?.role==='superadmin'?<Button size="sm" variant="outline" disabled={m.isPending} onClick={()=>{if(confirm('Confirma que este fornecedor atende ao seu estúdio e pode ser selecionado para pedidos de orçamento? Cada envio ainda exigirá sua aprovação.'))m.mutate({supplierId,confirmed:true});}}>Habilitar orçamentos</Button>:null;}
export default function ProcurementPanel(){const{user}=useAuth();const manager=user?.role==='admin'||user?.role==='superadmin';const q=trpc.studioRelations.procurement.useQuery(undefined,{enabled:manager,refetchInterval:30000});const artists=trpc.artists.list.useQuery(undefined,{enabled:manager});const utils=trpc.useUtils();const refresh=()=>utils.studioRelations.procurement.invalidate();const err=(e:{message:string})=>toast.error(e.message);
 const [showAll,setShowAll]=useState(false);const [materialSearch,setMaterialSearch]=useState('');
 const [template,setTemplate]=useState<{id?:number,name:string,body:string}|null>(null);const [draft,setDraft]=useState<{materialId:number,supplierId:number,quantity:number,body:string,variables:{key:string,value:string}[]}|null>(null);const [notify,setNotify]=useState<{materialId:number,artistId:number|null,enabled:boolean}|null>(null);
 const defaults=trpc.studioRelations.defaults.useMutation({onSuccess:refresh,onError:err});const save=trpc.studioRelations.saveTemplate.useMutation({onSuccess:()=>{refresh();setTemplate(null);},onError:err});const create=trpc.studioRelations.draft.useMutation({onSuccess:()=>{refresh();setDraft(null);toast.success('Rascunho salvo. Revise antes de aprovar o envio.');},onError:err});const approve=trpc.studioRelations.approve.useMutation({onSuccess:()=>{refresh();toast.success('Envio aprovado e aguardando processamento.');},onError:err});const cancel=trpc.studioRelations.cancel.useMutation({onSuccess:refresh,onError:err});const notification=trpc.studioRelations.notification.useMutation({onSuccess:()=>{refresh();setNotify(null);},onError:err});
 if(!manager)return null;const statuses:Record<string,string>={draft:'Rascunho — não enviado',approved:'Aprovado — aguardando envio',processing:'Envio em processamento; confira o provedor se persistir',sent:'Enviado',review:'Envio incerto — revisar no provedor',blocked:'Bloqueado — prepare novo rascunho após corrigir',cancelled:'Cancelado'};
 return <section className="my-6 rounded-xl border p-4 space-y-4"><h2 className="text-xl font-bold">Reposição e orçamentos</h2><p className="text-sm text-muted-foreground">Materiais do estúdio no estoque mínimo ou abaixo dele. O aviso ao artista ou ao estúdio é opcional. Nenhum orçamento é enviado sem aprovação do responsável; solicitar orçamento não efetua uma compra.</p>{q.error&&<p role="alert">Não foi possível carregar a reposição.</p>}<label className="flex gap-2"><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/>Mostrar todos os materiais para orçamento</label><Input aria-label="Buscar material para orçamento" placeholder="Buscar nome, marca ou especificação" value={materialSearch} onChange={e=>setMaterialSearch(e.target.value)}/><div className="space-y-3">{q.data?.materials.filter(m=>(showAll||(Number(m.minimumQuantity)>0&&Number(m.currentQuantity)<=Number(m.minimumQuantity)))&&materialDescription(m).toLowerCase().includes(materialSearch.toLowerCase())).map(m=>{const a=q.data.alerts.find(a=>a.materialId===m.id);return <article key={m.id} className="border rounded-lg p-3 space-y-2"><strong>{materialDescription(m)}</strong><p>Disponível: {m.currentQuantity} {m.unit} · Mínimo: {m.minimumQuantity}</p><p className="text-sm">Aviso WhatsApp: {a?.notifyEnabled?'ativado':'inativo'}{a?.notifiedAt?' · tentativa registrada neste ciclo de reposição':''}</p>{a?.lastError&&<p role="alert">{a.lastError}</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setNotify({materialId:m.id,artistId:a?.recipientArtistId||null,enabled:!!a?.notifyEnabled})}>Configurar aviso</Button><Button onClick={()=>setDraft({materialId:m.id,supplierId:q.data.contacts[0]?.id||0,quantity:Math.max(1,Number(m.minimumQuantity)-Number(m.currentQuantity)),body:q.data.templates[0]?.body||'',variables:[]})}>Preparar orçamento</Button></div></article>;})}{!q.isLoading&&!q.data?.materials.length&&<p>Nenhum material do estúdio precisa de reposição pelo mínimo configurado.</p>}</div>
 <h3 className="font-semibold">Modelos de orçamento</h3><div className="flex gap-2 flex-wrap"><Button variant="outline" onClick={()=>defaults.mutate()}>Adicionar modelos de orçamento</Button><Button variant="outline" onClick={()=>setTemplate({name:'',body:''})}>Criar modelo de orçamento</Button></div>{q.data?.templates.map(t=><article className="border rounded p-3 space-y-2" key={t.id}><strong>{t.name}</strong><p className="whitespace-pre-wrap text-sm">{t.body}</p><Button size="sm" variant="outline" onClick={()=>setTemplate(t)}>Editar modelo</Button></article>)}
 <h3 className="font-semibold">Pedidos e aprovações</h3>{q.data?.quotes.map(r=><article key={r.id} className="rounded border p-3 space-y-2"><strong>Orçamento #{r.id} · {statuses[r.status]||r.status}</strong><p>Destinatário: {r.recipientPhone} · Quantidade: {r.quantity}</p><p className="whitespace-pre-wrap">{r.message}</p>{r.lastError&&<p role="alert">{r.lastError}</p>}{r.status==='draft'&&<div className="flex gap-2"><Button disabled={approve.isPending} onClick={()=>{if(confirm('Aprovar o envio deste texto para o telefone exibido?'))approve.mutate({id:r.id,message:r.message,phone:r.recipientPhone});}}>Aprovar e enviar orçamento</Button><Button variant="outline" onClick={()=>cancel.mutate({id:r.id})}>Cancelar rascunho</Button></div>}</article>)}
 <Dialog open={!!template} onOpenChange={v=>{if(!v)setTemplate(null);}}><DialogContent><DialogHeader><DialogTitle>Modelo de orçamento</DialogTitle></DialogHeader>{template&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();save.mutate(template);}}><label>Nome<Input required value={template.name} onChange={e=>setTemplate({...template,name:e.target.value})}/></label><label>Mensagem<Textarea required rows={7} value={template.body} onChange={e=>setTemplate({...template,body:e.target.value})}/></label><p className="text-sm">Variáveis automáticas: {QUOTE_VARIABLES.map(v=>`{${v}}`).join(', ')}. Crie outras como {'{prazo_desejado}'} e preencha ao preparar o pedido.</p><Button disabled={save.isPending}>Salvar modelo de orçamento</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!draft} onOpenChange={v=>{if(!v)setDraft(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Preparar pedido de orçamento</DialogTitle></DialogHeader>{draft&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();create.mutate({...draft,variables:Object.fromEntries(draft.variables.map(x=>[x.key,x.value]))});}}><label>Fornecedor<select required className="block border rounded bg-background p-2 w-full" value={draft.supplierId||''} onChange={e=>setDraft({...draft,supplierId:Number(e.target.value)})}><option value="">Selecione</option>{q.data?.contacts.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>{!q.data?.contacts.length&&<p>Em Fornecedores, confirme “Habilitar orçamentos” no cadastro do parceiro do seu estúdio.</p>}<label>Quantidade a cotar<Input type="number" min="0.001" step="0.001" required value={draft.quantity} onChange={e=>setDraft({...draft,quantity:Number(e.target.value)})}/></label><label>Escolher modelo<select className="block border rounded bg-background p-2 w-full" defaultValue="" onChange={e=>{const t=q.data?.templates.find(t=>t.id===Number(e.target.value));if(t)setDraft({...draft,body:t.body});}}><option value="">Selecione ou escreva abaixo</option>{q.data?.templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><Textarea aria-label="Texto do orçamento" rows={7} required value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/><p className="text-sm">Os dados do material, estúdio e fornecedor serão preenchidos automaticamente. Revise o texto final após salvar o rascunho.</p><h4>Variáveis adicionais</h4>{draft.variables.map((v,i)=><div className="flex gap-2" key={i}><Input placeholder="prazo_desejado" aria-label={`Variável ${i+1}`} value={v.key} onChange={e=>setDraft({...draft,variables:draft.variables.map((x,j)=>i===j?{...x,key:e.target.value}:x)})}/><Input placeholder="até sexta-feira" aria-label={`Valor ${i+1}`} value={v.value} onChange={e=>setDraft({...draft,variables:draft.variables.map((x,j)=>i===j?{...x,value:e.target.value}:x)})}/></div>)}<Button type="button" variant="outline" disabled={draft.variables.length>=30} onClick={()=>setDraft({...draft,variables:[...draft.variables,{key:'',value:''}]})}>Adicionar variável</Button><Button type="submit" disabled={create.isPending||!draft.supplierId}>Salvar rascunho para revisão</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!notify} onOpenChange={v=>{if(!v)setNotify(null);}}><DialogContent><DialogHeader><DialogTitle>Aviso de reposição</DialogTitle></DialogHeader>{notify&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();notification.mutate(notify);}}><label>Quem recebe<select className="block border rounded bg-background p-2" value={notify.artistId||''} onChange={e=>setNotify({...notify,artistId:Number(e.target.value)||null})}><option value="">Estúdio — telefone das configurações</option>{artists.data?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><p>O artista precisa estar vinculado como usuário deste material no estoque do estúdio. O sistema valida esse vínculo antes de salvar.</p><label className="flex gap-2"><input type="checkbox" checked={notify.enabled} onChange={e=>setNotify({...notify,enabled:e.target.checked})}/>Ativar aviso automático de reposição</label><p className="text-sm">Um aviso por ciclo de estoque baixo. Um novo ciclo começa quando o saldo fica acima do mínimo e volta a baixar. Requer WhatsApp testado.</p><Button disabled={notification.isPending}>Salvar aviso</Button></form>}</DialogContent></Dialog>
 </section>;
}
