import {useState} from 'react';
import {trpc} from '@/lib/trpc';
import {toast} from 'sonner';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from './ui/dialog';
export default function ReceiveMaterial({material,onClose}:{material:{id:number;name:string;unit:string;unitCost:string};onClose:()=>void}){
 const [receiptKey]=useState(()=>crypto.randomUUID());const [supplierId,setSupplier]=useState('');const [lot,setLot]=useState('');const [expires,setExpires]=useState('');const [quantity,setQuantity]=useState('');const [cost,setCost]=useState(material.unitCost);
 const suppliers=trpc.suppliers.list.useQuery({activeOnly:true});const batches=trpc.pod.inventory.batches.useQuery({tenantMaterialId:material.id});const utils=trpc.useUtils();
 const receive=trpc.pod.inventory.receive.useMutation({onSuccess:()=>{utils.pod.inventory.invalidate();toast.success('Recebimento registrado, com lote e fornecedor.');onClose()},onError:e=>toast.error(e.message)});
 return <Dialog open onOpenChange={v=>!v&&!receive.isPending&&onClose()}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Receber material: {material.name}</DialogTitle></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();receive.mutate({tenantMaterialId:material.id,receiptKey,supplierId:Number(supplierId),lot,expiresAt:expires||undefined,quantity:quantity.replace(',','.'),unitCost:cost.replace(',','.')})}}><label className="block">Fornecedor<select className="block w-full rounded border bg-background p-2" value={supplierId} onChange={e=>setSupplier(e.target.value)} required><option value="">Selecione</option>{suppliers.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{suppliers.error&&<p role="alert">{suppliers.error.message}</p>}<label className="block">Lote<Input required maxLength={120} value={lot} onChange={e=>setLot(e.target.value)}/></label><label className="block">Validade (se informada na embalagem)<Input type="date" value={expires} onChange={e=>setExpires(e.target.value)}/></label><label className="block">Quantidade recebida em {material.unit}<Input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><p className="text-xs text-muted-foreground">Informe a quantidade na unidade de consumo. Exemplo: 2 caixas de 20 unidades correspondem a 40 unidades.</p><label className="block">Custo por {material.unit} (R$)<Input required inputMode="decimal" value={cost} onChange={e=>setCost(e.target.value)}/></label><Button disabled={receive.isPending||!supplierId}>{receive.isPending?'Registrando…':'Registrar recebimento'}</Button></form><h3 className="font-semibold">Lotes recebidos</h3>{batches.error&&<p role="alert">{batches.error.message}</p>}{batches.data?.map(b=><article key={b.id} className="rounded border p-2 text-sm">Lote {b.lot} · Saldo {b.remainingQuantity} {material.unit}<br/>{b.supplierName} · Validade: {b.expiresAt?b.expiresAt.slice(0,10).split('-').reverse().join('/'):'não informada'}</article>)}</DialogContent></Dialog>;
}
