import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {rm} from 'node:fs/promises';
const here=path.dirname(fileURLToPath(import.meta.url));
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import {createElement, act} from 'react';
import {createRoot} from 'react-dom/client';
import assert from 'node:assert/strict';
const dom=new JSDOM('<div id="root"></div>',{url:'https://example.test/anamnese/test'});
globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.HTMLElement=dom.window.HTMLElement;globalThis.IS_REACT_ACT_ENVIRONMENT=true;window.scrollTo=()=>{};
const ui=`import React from 'react'; export const Button=({children,variant,...p})=>React.createElement('button',p,children); export const Input=p=>React.createElement('input',p); export const Label=({children,...p})=>React.createElement('label',p,children); export const Textarea=p=>React.createElement('textarea',p); export const RadioGroup=()=>null; export const RadioGroupItem=()=>null; export const Checkbox=()=>null; export const Card=({children,...p})=>React.createElement('div',p,children); export const CardHeader=Card; export const CardContent=Card; export const CardTitle=Card; export const CardDescription=Card;`;
const mocks={wouter:`export const useRoute=()=>[true,{token:'test'}];`,'@/lib/trpc':`export const trpc={anamnese:{getRequestByToken:{useQuery:()=>({data:globalThis.fixture,isLoading:false})},submitAnamnese:{useMutation:(callbacks)=>({mutate:(payload)=>{globalThis.sent.push(payload);globalThis.callbacks=callbacks;},mutateAsync:async(payload)=>{globalThis.sent.push(payload);globalThis.callbacks=callbacks;}})}}};`,'@/hooks/useSyncToast':`export const useSyncToast=()=>({notifySync:()=>{globalThis.syncCalls++}});`,sonner:`export const toast={success:()=>{},error:()=>{}};`,'lucide-react':`import React from 'react';const Icon=p=>React.createElement('svg',p);export const Loader2=Icon,CheckCircle2=Icon,ChevronLeft=Icon,ChevronRight=Icon,AlertCircle=Icon,MapPin=Icon;`,'@shared/anamnese.schema.json':`export default {title:'Ficha',subtitle:'Teste',steps:[{id:'a',title:'Primeira',fields:[{key:'client_name',label:'Nome',type:'text'}]},{id:'b',title:'Consentimento',fields:[]}]};`};
async function compile(file){const output=path.join(here, '.compiled-'+(file==='before'?'before':'fixed')+'.mjs'); const source=file==='before'?{stdin:{contents:`import React,{useState} from 'react';export default function OldButton(){const [step,setStep]=useState(0);return <button onClick={()=>setStep(1)}>{step===0?<>Próximo<svg /></>:'Enviar Ficha'}</button>;}`,loader:'jsx',resolveDir:here}}:{entryPoints:[file]}; await build({...source,outfile:output,bundle:true,format:'esm',platform:'node',jsx:'automatic',external:['react'],plugins:[{name:'mocks',setup(b){b.onResolve({filter:/^(@\/|@shared|wouter|sonner|lucide-react)/},a=>({path:a.path,namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:mocks[a.path]||ui,loader:'js'}));}}]});const Page=(await import(output)).default;await rm(output);return Page;}
function translateText(){const walker=document.createTreeWalker(document.getElementById('root'),window.NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes){if(!n.textContent.trim()||n.parentElement?.closest('[translate="no"]'))continue;const font=document.createElement('font');font.textContent=n.textContent;n.replaceWith(font);}}
function button(label){return [...document.querySelectorAll('button')].find(b=>b.textContent.includes(label));}
async function run(file,shouldFail){const Page=await compile(file);let errors=[];let root=createRoot(document.getElementById('root'),{onUncaughtError:e=>errors.push(e)});globalThis.fixture={client:{name:'Teste',phone:'31999999999'}};globalThis.sent=[];globalThis.syncCalls=0;await act(async()=>root.render(createElement(Page)));if(!shouldFail) assert.equal(document.querySelector('input').getAttribute('aria-label'),'Nome');translateText();try { await act(async()=>button('Próximo').click()); } catch(e) { errors.push(e); } if(shouldFail){assert(errors.some(e=>e.name==='NotFoundError'),'old page should reproduce NotFoundError');await act(async()=>root.unmount());console.log('PASS: original page reproduces removeChild after translated text');return;}
assert.equal(errors.length,0);translateText();await act(async()=>button('Enviar Ficha').click());assert.equal(sent.length,1);assert(button('Enviando').disabled);await act(async()=>callbacks.onError({message:'Falha de teste'}));assert(document.querySelector('[role="alert"]').textContent.includes('Falha de teste'));assert.equal(document.querySelector('[role="status"]'),null);translateText();await act(async()=>button('Enviar Ficha').click());await act(async()=>callbacks.onSuccess());assert(document.querySelector('[role="status"]').textContent.includes('Ficha enviada!'));assert.equal(errors.length,0);assert.equal(syncCalls,0);await act(async()=>root.unmount());console.log('PASS: translated navigation, send, retry and success; no admin sync call');}
await run('before',true);await run(process.env.ANAMNESE_SOURCE || path.resolve(here,'../../client/src/pages/PublicAnamnese.tsx'),false);
